// Generated by gencpp from file server_client/twoaddResponse.msg
// DO NOT EDIT!


#ifndef SERVER_CLIENT_MESSAGE_TWOADDRESPONSE_H
#define SERVER_CLIENT_MESSAGE_TWOADDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_client
{
template <class ContainerAllocator>
struct twoaddResponse_
{
  typedef twoaddResponse_<ContainerAllocator> Type;

  twoaddResponse_()
    : ret(0)  {
    }
  twoaddResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
  (void)_alloc;
    }



   typedef int32_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::server_client::twoaddResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_client::twoaddResponse_<ContainerAllocator> const> ConstPtr;

}; // struct twoaddResponse_

typedef ::server_client::twoaddResponse_<std::allocator<void> > twoaddResponse;

typedef boost::shared_ptr< ::server_client::twoaddResponse > twoaddResponsePtr;
typedef boost::shared_ptr< ::server_client::twoaddResponse const> twoaddResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_client::twoaddResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_client::twoaddResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_client::twoaddResponse_<ContainerAllocator1> & lhs, const ::server_client::twoaddResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_client::twoaddResponse_<ContainerAllocator1> & lhs, const ::server_client::twoaddResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server_client::twoaddResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_client::twoaddResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_client::twoaddResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_client::twoaddResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_client::twoaddResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_client::twoaddResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_client::twoaddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bd113e2f12c9c571d32a0bd71d59b8d";
  }

  static const char* value(const ::server_client::twoaddResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bd113e2f12c9c57ULL;
  static const uint64_t static_value2 = 0x1d32a0bd71d59b8dULL;
};

template<class ContainerAllocator>
struct DataType< ::server_client::twoaddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_client/twoaddResponse";
  }

  static const char* value(const ::server_client::twoaddResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_client::twoaddResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#服务器响应的数据\n"
"\n"
"int32 ret\n"
"\n"
;
  }

  static const char* value(const ::server_client::twoaddResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_client::twoaddResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct twoaddResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_client::twoaddResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_client::twoaddResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_CLIENT_MESSAGE_TWOADDRESPONSE_H
