// Generated by gencpp from file server_client/twoadd.msg
// DO NOT EDIT!


#ifndef SERVER_CLIENT_MESSAGE_TWOADD_H
#define SERVER_CLIENT_MESSAGE_TWOADD_H

#include <ros/service_traits.h>


#include <server_client/twoaddRequest.h>
#include <server_client/twoaddResponse.h>


namespace server_client
{

struct twoadd
{

typedef twoaddRequest Request;
typedef twoaddResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct twoadd
} // namespace server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_client::twoadd > {
  static const char* value()
  {
    return "da303ca83c249449e0d5931b4ba7bf73";
  }

  static const char* value(const ::server_client::twoadd&) { return value(); }
};

template<>
struct DataType< ::server_client::twoadd > {
  static const char* value()
  {
    return "server_client/twoadd";
  }

  static const char* value(const ::server_client::twoadd&) { return value(); }
};


// service_traits::MD5Sum< ::server_client::twoaddRequest> should match
// service_traits::MD5Sum< ::server_client::twoadd >
template<>
struct MD5Sum< ::server_client::twoaddRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_client::twoadd >::value();
  }
  static const char* value(const ::server_client::twoaddRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client::twoaddRequest> should match
// service_traits::DataType< ::server_client::twoadd >
template<>
struct DataType< ::server_client::twoaddRequest>
{
  static const char* value()
  {
    return DataType< ::server_client::twoadd >::value();
  }
  static const char* value(const ::server_client::twoaddRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_client::twoaddResponse> should match
// service_traits::MD5Sum< ::server_client::twoadd >
template<>
struct MD5Sum< ::server_client::twoaddResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_client::twoadd >::value();
  }
  static const char* value(const ::server_client::twoaddResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_client::twoaddResponse> should match
// service_traits::DataType< ::server_client::twoadd >
template<>
struct DataType< ::server_client::twoaddResponse>
{
  static const char* value()
  {
    return DataType< ::server_client::twoadd >::value();
  }
  static const char* value(const ::server_client::twoaddResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_CLIENT_MESSAGE_TWOADD_H
