// Generated by gencpp from file server_client/twoaddRequest.msg
// DO NOT EDIT!


#ifndef SERVER_CLIENT_MESSAGE_TWOADDREQUEST_H
#define SERVER_CLIENT_MESSAGE_TWOADDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_client
{
template <class ContainerAllocator>
struct twoaddRequest_
{
  typedef twoaddRequest_<ContainerAllocator> Type;

  twoaddRequest_()
    : num1(0)
    , num2(0)  {
    }
  twoaddRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::server_client::twoaddRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_client::twoaddRequest_<ContainerAllocator> const> ConstPtr;

}; // struct twoaddRequest_

typedef ::server_client::twoaddRequest_<std::allocator<void> > twoaddRequest;

typedef boost::shared_ptr< ::server_client::twoaddRequest > twoaddRequestPtr;
typedef boost::shared_ptr< ::server_client::twoaddRequest const> twoaddRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_client::twoaddRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_client::twoaddRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_client::twoaddRequest_<ContainerAllocator1> & lhs, const ::server_client::twoaddRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_client::twoaddRequest_<ContainerAllocator1> & lhs, const ::server_client::twoaddRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server_client::twoaddRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_client::twoaddRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_client::twoaddRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_client::twoaddRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_client::twoaddRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_client::twoaddRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_client::twoaddRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68f3979e1a90aac7d1c75a1096d1e60";
  }

  static const char* value(const ::server_client::twoaddRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68f3979e1a90aacULL;
  static const uint64_t static_value2 = 0x7d1c75a1096d1e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::server_client::twoaddRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_client/twoaddRequest";
  }

  static const char* value(const ::server_client::twoaddRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_client::twoaddRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#客户端请求时发送的数据\n"
"int32 num1\n"
"int32 num2\n"
;
  }

  static const char* value(const ::server_client::twoaddRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_client::twoaddRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct twoaddRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_client::twoaddRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_client::twoaddRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_CLIENT_MESSAGE_TWOADDREQUEST_H
